const operators = {
  '&': 'AND',
  '|': 'PIPE',
  '(': 'OPEN_PAREN',
  ')': 'CLOSE_PAREN',
  '[': 'OPEN_BRACKET',
  ']': 'CLOSE_BRACKET',
  '[[': 'DOPEN_BRACKET',
  ']]': 'DCLOSE_BRACKET',
  '>': 'GREAT',
  '<': 'LESS',
  '&&': 'AND_IF',
  '||': 'OR_IF',
  ';;': 'DOUBLE_SEMICOLON',
  '<<': 'DOUBLE_LESS',
  '>>': 'DOUBLE_GREAT',
  '<&': 'LESS_AND',
  '>&': 'GREAT_AND',
  '<>': 'LESS_GREAT',
  '<<-': 'DOUBLE_LESS_DASH',
  '>|': 'CLOBBER',
  ';': 'SEMICOLON',
};

export default operators;
