const reservedWords = {
  'if': 'If',
  'then': 'Then',
  'else': 'Else',
  'elif': 'Elif',
  'fi': 'Fi',
  'do': 'Do',
  'done': 'Done',
  'case': 'Case',
  'esac': 'Esac',
  'while': 'While',
  'until': 'Until',
  'for': 'For',
  'in': 'In',
  '{': 'Lbrace',
  '}': 'Rbrace',
  '!': 'Bang',
  '=': 'Equal',
  '==': 'Equal',
  '!=': 'NotEqual',
  '<': 'LessThan',
  '<=': 'LessThanOrEqual',
  '>': 'GreaterThan',
  '>=': 'GreaterThanOrEqual',
  '&&': 'And',
  '||': 'Or',
  '-eq': 'Equal',
  '-ne': 'NotEqual',
  '-lt': 'LessThan',
  '-le': 'LessThanOrEqual',
  '-gt': 'GreaterThan',
  '-ge': 'GreaterThanOrEqual',
  '-a': 'And',
  '-o': 'Or',
  '-z': 'IsStringNull',
  '-n': 'IsStringNotNull',
  '-d': 'IsDirectory',
  '-e': 'FileExists',
  '-f': 'IsFile',
  '-s': 'IsFileNotEmpty',
  '-r': 'IsReadable',
  '-w': 'IsWritable',
  '-x': 'IsExecutable',
};

export default reservedWords;
